### PR TITLE
Add DAP

### PR DESCRIPTION
**Pull request by FinnRG**
Adds basic support for nvim-dap, nvim-dap-ui and DAPInstall.

TODO!

- [x] Keybindings
- [x] which-key mappings
- [x] Add information to README.md
- [x] Sensible defaults
- [ ] Testing

Screenshot_2021-09-14-32_1920x1080

### CODE REVIEW

**Comment by samrathchadha** [comment]
hey @Pyther99 really appreciate this pr and the last one! thank you so much!

**Comment by samrathchadha** [comment]
So I've been using your fork and would you mind making a branch on this repo? I'll give you the access now, becomes easier to switch between configs without having to move your `kyotorc` folder too much.

**Comment by samrathchadha** [comment]
@Pyther99 the branch isn't working at all...

**Comment by FinnRG** [comment]
> @Pyther99 the branch isn't working at all...

I just tried a fresh install following the [Installation.md](https://github.com/samrath2007/kyoto.nvim/wiki/Installation) and everything is working fine. What exactly isn't working?

**Comment by samrathchadha** [comment]
Basically the debugger,
image
I have all these debuggers installed but in lets say a python file, there isn't any debugging..
image

**Comment by FinnRG** [comment]
You need to set a breakpoint first and then execute the file with `continue`.(\<leader\>db for Breakpoint and \<leader\>dc for continue (using the newest version of this branch) ) 

Screenshot_2021-09-15-39_1920x1080

**Comment by FinnRG** [comment]
@samrath2007 I'll first merge this PR into the DAP branch and open a stabilization PR

**Comment by samrathchadha** [comment]
Cool thanks

**Pull request merged**
